### ISSUE TITLE
Corebird 'Compose Message Box' resizes incorrectly

### ISSUE THREAD

**Issue by Vistaus** [x-tabdeveloping/Edge-Dark#2]
https://github.com/baedert/corebird/issues/597

As you can see in the linked bug report, the Corebird dev says it's a theming bug and provided some CSS code. So I'm filing it here, hoping you can fix it.

**Comment by x-tabdeveloping** [comment]
Thanks for reporting, i fixed the bug. I will try Corebird probably, to release new bugs.

**Comment by Vistaus** [comment]
Thanks for fixing it! :-)
